# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Pirate Party ⓋT
email: ---
description: > # this means to ignore newlines until "baseurl:"
   Promoting privacy, transparent government & innovation via copyright reform and the elimination of patent laws.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://piratepartyvt.github.io/" # the base hostname & protocol for your site
twitter_username: PiratePartyVT
github_username:  piratepartyvt
pirateirc_channel: piratepartyvt

# Build settings
markdown: kramdown
